version: "3.1"

services:
  news:
    build:
      context: .
    container_name: news
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./data:/data
    restart: always
    tty: true
    ports:
      - 9999:9999
